name: Montreal Collective
description: A collection of Montreal's best tech companies, startups, investors, and events
keywords: montreal, startups, companies, events, tech, investors, meetups, quebec, canada, technology

exclude: [_less, _img, _css, _js, _assets, _icons, node_modules, s3_website.yml, package.json, README.md, GruntFile.js, Gemfile, Gemfile.lock]
safe: false
source: .
destination: ./_site

port: 3000